Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Tests\\Integration\\DatabaseStructureTest",
            "name": "DatabaseStructureTest",
            "summary": "",
            "url": "classes/App-Tests-Integration-DatabaseStructureTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Integration\\DatabaseStructureTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/App-Tests-Integration-DatabaseStructureTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Integration\\DatabaseStructureTest\u003A\u003AtestDatabaseTablesExist\u0028\u0029",
            "name": "testDatabaseTablesExist",
            "summary": "",
            "url": "classes/App-Tests-Integration-DatabaseStructureTest.html#method_testDatabaseTablesExist"
        },                {
            "fqsen": "\\App\\Tests\\Integration\\DatabaseStructureTest\u003A\u003AtableExists\u0028\u0029",
            "name": "tableExists",
            "summary": "",
            "url": "classes/App-Tests-Integration-DatabaseStructureTest.html#method_tableExists"
        },                {
            "fqsen": "\\App\\Tests\\Integration\\DatabaseStructureTest\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/App-Tests-Integration-DatabaseStructureTest.html#property_connection"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Domain\\Common\\Entity\\EntityBaseTest",
            "name": "EntityBaseTest",
            "summary": "Tests\u0020for\u0020the\u0020EntityBase\u0020class.",
            "url": "classes/App-Tests-Unit-Domain-Common-Entity-EntityBaseTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Domain\\Common\\Entity\\EntityBaseTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "Sets\u0020up\u0020the\u0020test\u0020environment\u0020with\u0020a\u0020mock\u0020of\u0020EntityBase.",
            "url": "classes/App-Tests-Unit-Domain-Common-Entity-EntityBaseTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Domain\\Common\\Entity\\EntityBaseTest\u003A\u003AtestGetId\u0028\u0029",
            "name": "testGetId",
            "summary": "Tests\u0020if\u0020the\u0020entity\u0020has\u0020a\u0020valid\u0020UUID.",
            "url": "classes/App-Tests-Unit-Domain-Common-Entity-EntityBaseTest.html#method_testGetId"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Domain\\Common\\Entity\\EntityBaseTest\u003A\u003A\u0024entity",
            "name": "entity",
            "summary": "",
            "url": "classes/App-Tests-Unit-Domain-Common-Entity-EntityBaseTest.html#property_entity"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\Common\\Entity\\ConcreteThing",
            "name": "ConcreteThing",
            "summary": "Concrete\u0020class\u0020extending\u0020Thing\u0020for\u0020testing\u0020purposes.",
            "url": "classes/App-Tests-Domain-Common-Entity-ConcreteThing.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\Common\\Entity\\ThingTest",
            "name": "ThingTest",
            "summary": "Unit\u0020tests\u0020for\u0020the\u0020Thing\u0020class.",
            "url": "classes/App-Tests-Domain-Common-Entity-ThingTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\Common\\Entity\\ThingTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "Sets\u0020up\u0020the\u0020test\u0020environment\u0020by\u0020creating\u0020a\u0020new\u0020instance\u0020of\u0020ConcreteThing.",
            "url": "classes/App-Tests-Domain-Common-Entity-ThingTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\Common\\Entity\\ThingTest\u003A\u003AtestThingCreationWithName\u0028\u0029",
            "name": "testThingCreationWithName",
            "summary": "Tests\u0020that\u0020the\u0020Thing\u0020instance\u0020is\u0020created\u0020with\u0020the\u0020specified\u0020name.",
            "url": "classes/App-Tests-Domain-Common-Entity-ThingTest.html#method_testThingCreationWithName"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\Common\\Entity\\ThingTest\u003A\u003AtestSetName\u0028\u0029",
            "name": "testSetName",
            "summary": "Tests\u0020setting\u0020and\u0020getting\u0020the\u0020name\u0020property.",
            "url": "classes/App-Tests-Domain-Common-Entity-ThingTest.html#method_testSetName"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\Common\\Entity\\ThingTest\u003A\u003A\u0024thing",
            "name": "thing",
            "summary": "",
            "url": "classes/App-Tests-Domain-Common-Entity-ThingTest.html#property_thing"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\DeviceTest",
            "name": "DeviceTest",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-DeviceTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\DeviceTest\u003A\u003AtestDeviceCreation\u0028\u0029",
            "name": "testDeviceCreation",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-DeviceTest.html#method_testDeviceCreation"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\SessionTest",
            "name": "SessionTest",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-SessionTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\SessionTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-SessionTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\SessionTest\u003A\u003AtestSessionCreation\u0028\u0029",
            "name": "testSessionCreation",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-SessionTest.html#method_testSessionCreation"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\SessionTest\u003A\u003AtestSessionExpiration\u0028\u0029",
            "name": "testSessionExpiration",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-SessionTest.html#method_testSessionExpiration"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\SessionTest\u003A\u003AtestDeviceTypeInSession\u0028\u0029",
            "name": "testDeviceTypeInSession",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-SessionTest.html#method_testDeviceTypeInSession"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\SessionTest\u003A\u003A\u0024session",
            "name": "session",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-SessionTest.html#property_session"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\SessionTest\u003A\u003A\u0024device",
            "name": "device",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-SessionTest.html#property_device"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest",
            "name": "UserTest",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestUserCreation\u0028\u0029",
            "name": "testUserCreation",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testUserCreation"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestAddAndRemoveSession\u0028\u0029",
            "name": "testAddAndRemoveSession",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testAddAndRemoveSession"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestCloseAllSessions\u0028\u0029",
            "name": "testCloseAllSessions",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testCloseAllSessions"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestSetUsername\u0028\u0029",
            "name": "testSetUsername",
            "summary": "Tests\u0020the\u0020setUsername\u0020method\u0020to\u0020ensure\u0020it\u0020correctly\u0020sets\u0020the\u0020username.",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testSetUsername"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestSetLastLogin\u0028\u0029",
            "name": "testSetLastLogin",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testSetLastLogin"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestActivateAndDeactivateUser\u0028\u0029",
            "name": "testActivateAndDeactivateUser",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testActivateAndDeactivateUser"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestSetEmail\u0028\u0029",
            "name": "testSetEmail",
            "summary": "Tests\u0020the\u0020setEmail\u0020method\u0020to\u0020ensure\u0020it\u0020correctly\u0020sets\u0020the\u0020email\u0020address.",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testSetEmail"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestSetPasswordHash\u0028\u0029",
            "name": "testSetPasswordHash",
            "summary": "Tests\u0020the\u0020setPasswordHash\u0020method\u0020to\u0020ensure\u0020it\u0020correctly\u0020updates\u0020the\u0020password\u0020hash.",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testSetPasswordHash"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003AtestSetRole\u0028\u0029",
            "name": "testSetRole",
            "summary": "Tests\u0020the\u0020setRole\u0020method\u0020to\u0020ensure\u0020it\u0020correctly\u0020updates\u0020the\u0020role.",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#method_testSetRole"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#property_user"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#property_password"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity\\UserTest\u003A\u003A\u0024role",
            "name": "role",
            "summary": "",
            "url": "classes/App-Tests-Domain-UserManagement-Entity-UserTest.html#property_role"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest",
            "name": "PasswordTest",
            "summary": "Unit\u0020tests\u0020for\u0020the\u0020Password\u0020value\u0020object.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestPasswordCreationWithValidPassword\u0028\u0029",
            "name": "testPasswordCreationWithValidPassword",
            "summary": "Tests\u0020that\u0020a\u0020password\u0020meeting\u0020all\u0020complexity\u0020requirements\u0020can\u0020be\u0020created\u0020successfully.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testPasswordCreationWithValidPassword"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestPasswordTooShortThrowsException\u0028\u0029",
            "name": "testPasswordTooShortThrowsException",
            "summary": "Tests\u0020that\u0020an\u0020exception\u0020is\u0020thrown\u0020when\u0020a\u0020password\u0020is\u0020shorter\u0020than\u00208\u0020characters.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testPasswordTooShortThrowsException"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestPasswordWithoutUppercaseThrowsException\u0028\u0029",
            "name": "testPasswordWithoutUppercaseThrowsException",
            "summary": "Tests\u0020that\u0020an\u0020exception\u0020is\u0020thrown\u0020when\u0020a\u0020password\u0020does\u0020not\u0020contain\u0020an\u0020uppercase\u0020letter.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testPasswordWithoutUppercaseThrowsException"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestPasswordWithoutLowercaseThrowsException\u0028\u0029",
            "name": "testPasswordWithoutLowercaseThrowsException",
            "summary": "Tests\u0020that\u0020an\u0020exception\u0020is\u0020thrown\u0020when\u0020a\u0020password\u0020does\u0020not\u0020contain\u0020a\u0020lowercase\u0020letter.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testPasswordWithoutLowercaseThrowsException"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestPasswordWithoutDigitThrowsException\u0028\u0029",
            "name": "testPasswordWithoutDigitThrowsException",
            "summary": "Tests\u0020that\u0020an\u0020exception\u0020is\u0020thrown\u0020when\u0020a\u0020password\u0020does\u0020not\u0020contain\u0020a\u0020digit.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testPasswordWithoutDigitThrowsException"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestPasswordWithoutSpecialCharacterThrowsException\u0028\u0029",
            "name": "testPasswordWithoutSpecialCharacterThrowsException",
            "summary": "Tests\u0020that\u0020an\u0020exception\u0020is\u0020thrown\u0020when\u0020a\u0020password\u0020does\u0020not\u0020contain\u0020a\u0020special\u0020character.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testPasswordWithoutSpecialCharacterThrowsException"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestHashedPasswordDoesNotEqualPlainPassword\u0028\u0029",
            "name": "testHashedPasswordDoesNotEqualPlainPassword",
            "summary": "Tests\u0020that\u0020the\u0020hashed\u0020password\u0020is\u0020not\u0020equal\u0020to\u0020the\u0020plain\u0020password\u0020directly.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testHashedPasswordDoesNotEqualPlainPassword"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestVerifyReturnsTrueForCorrectPassword\u0028\u0029",
            "name": "testVerifyReturnsTrueForCorrectPassword",
            "summary": "Tests\u0020that\u0020the\u0020verify\u0020method\u0020returns\u0020true\u0020for\u0020the\u0020correct\u0020password.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testVerifyReturnsTrueForCorrectPassword"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\PasswordTest\u003A\u003AtestVerifyReturnsFalseForIncorrectPassword\u0028\u0029",
            "name": "testVerifyReturnsFalseForIncorrectPassword",
            "summary": "Tests\u0020that\u0020the\u0020verify\u0020method\u0020returns\u0020false\u0020for\u0020an\u0020incorrect\u0020password.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-PasswordTest.html#method_testVerifyReturnsFalseForIncorrectPassword"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest",
            "name": "RoleTest",
            "summary": "Unit\u0020test\u0020for\u0020the\u0020Role\u0020value\u0020object.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest\u003A\u003AtestValidRoleCreation\u0028\u0029",
            "name": "testValidRoleCreation",
            "summary": "Tests\u0020the\u0020successful\u0020creation\u0020of\u0020a\u0020Role\u0020with\u0020valid\u0020roles.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html#method_testValidRoleCreation"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest\u003A\u003AvalidRolesProvider\u0028\u0029",
            "name": "validRolesProvider",
            "summary": "Data\u0020provider\u0020for\u0020valid\u0020roles.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html#method_validRolesProvider"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest\u003A\u003AtestInvalidRoleCreation\u0028\u0029",
            "name": "testInvalidRoleCreation",
            "summary": "Tests\u0020that\u0020an\u0020exception\u0020is\u0020thrown\u0020for\u0020an\u0020invalid\u0020role.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html#method_testInvalidRoleCreation"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest\u003A\u003AtestIsEqual\u0028\u0029",
            "name": "testIsEqual",
            "summary": "Tests\u0020that\u0020the\u0020isEqual\u0020method\u0020correctly\u0020compares\u0020two\u0020roles.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html#method_testIsEqual"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest\u003A\u003AtestIsAdmin\u0028\u0029",
            "name": "testIsAdmin",
            "summary": "Tests\u0020that\u0020the\u0020isAdmin\u0020method\u0020correctly\u0020identifies\u0020admin\u0020roles.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html#method_testIsAdmin"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest\u003A\u003AtestIsTeacher\u0028\u0029",
            "name": "testIsTeacher",
            "summary": "Tests\u0020that\u0020the\u0020isTeacher\u0020method\u0020correctly\u0020identifies\u0020teacher\u0020roles.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html#method_testIsTeacher"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest\u003A\u003AtestIsThirdLevelTeacher\u0028\u0029",
            "name": "testIsThirdLevelTeacher",
            "summary": "Tests\u0020that\u0020the\u0020isThirdLevelTeacher\u0020method\u0020correctly\u0020identifies\u0020third\u002Dlevel\u0020teacher\u0020roles.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html#method_testIsThirdLevelTeacher"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject\\RoleTest\u003A\u003AtestIsPrincipal\u0028\u0029",
            "name": "testIsPrincipal",
            "summary": "Tests\u0020that\u0020the\u0020isPrincipal\u0020method\u0020correctly\u0020identifies\u0020principal\u0020roles.",
            "url": "classes/App-Tests-Domain-UserManagement-ValueObject-RoleTest.html#method_testIsPrincipal"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest",
            "name": "BaseEntityRepositoryTest",
            "summary": "Unit\u0020tests\u0020for\u0020the\u0020BaseEntityRepository\u0020class.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestFindById\u0028\u0029",
            "name": "testFindById",
            "summary": "Tests\u0020that\u0020findById\u0020retrieves\u0020an\u0020entity\u0020by\u0020its\u0020unique\u0020identifier.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testFindById"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestFindAllWithoutDeleted\u0028\u0029",
            "name": "testFindAllWithoutDeleted",
            "summary": "Tests\u0020that\u0020findAll\u0020retrieves\u0020all\u0020entities\u0020that\u0020are\u0020not\u0020soft\u002Ddeleted.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testFindAllWithoutDeleted"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestSave\u0028\u0029",
            "name": "testSave",
            "summary": "Tests\u0020that\u0020save\u0020calls\u0020persist\u0020and\u0020flush\u0020on\u0020the\u0020entity\u0020manager.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testSave"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestSoftDelete\u0028\u0029",
            "name": "testSoftDelete",
            "summary": "Tests\u0020that\u0020softDelete\u0020marks\u0020an\u0020entity\u0020as\u0020deleted\u0020and\u0020flushes\u0020the\u0020entity\u0020manager.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testSoftDelete"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestDelete\u0028\u0029",
            "name": "testDelete",
            "summary": "Tests\u0020that\u0020delete\u0020removes\u0020an\u0020entity\u0020permanently\u0020and\u0020flushes\u0020the\u0020entity\u0020manager.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testDelete"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestFindAllWithDeleted\u0028\u0029",
            "name": "testFindAllWithDeleted",
            "summary": "Tests\u0020that\u0020findAll\u0020retrieves\u0020all\u0020entities,\u0020including\u0020soft\u002Ddeleted\u0020ones\u0020when\u0020requested.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testFindAllWithDeleted"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestRestore\u0028\u0029",
            "name": "testRestore",
            "summary": "Tests\u0020that\u0020restore\u0020reverts\u0020an\u0020entity\u0027s\u0020soft\u0020deletion\u0020and\u0020flushes\u0020the\u0020entity\u0020manager.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testRestore"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestExistsReturnsTrueWhenEntityExists\u0028\u0029",
            "name": "testExistsReturnsTrueWhenEntityExists",
            "summary": "Tests\u0020that\u0020exists\u0020returns\u0020true\u0020when\u0020an\u0020entity\u0020with\u0020the\u0020specified\u0020identifier\u0020exists.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testExistsReturnsTrueWhenEntityExists"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence\\BaseEntityRepositoryTest\u003A\u003AtestExistsReturnsFalseWhenEntityDoesNotExist\u0028\u0029",
            "name": "testExistsReturnsFalseWhenEntityDoesNotExist",
            "summary": "Tests\u0020that\u0020exists\u0020returns\u0020false\u0020when\u0020no\u0020entity\u0020with\u0020the\u0020specified\u0020identifier\u0020is\u0020found.",
            "url": "classes/App-Tests-Unit-Infrastructure-Persistence-BaseEntityRepositoryTest.html#method_testExistsReturnsFalseWhenEntityDoesNotExist"
        },                {
            "fqsen": "\\App\\Tests\\Infrastructure\\StateProcessor\\BaseStateProcessorTest",
            "name": "BaseStateProcessorTest",
            "summary": "Unit\u0020tests\u0020for\u0020BaseStateProcessor,\u0020which\u0020handles\u0020persistence\nand\u0020soft\u0020deletion\u0020logic\u0020for\u0020API\u0020Platform\u0020entities.",
            "url": "classes/App-Tests-Infrastructure-StateProcessor-BaseStateProcessorTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Infrastructure\\StateProcessor\\BaseStateProcessorTest\u003A\u003AtestProcessPersistsEntityForNonDeleteOperation\u0028\u0029",
            "name": "testProcessPersistsEntityForNonDeleteOperation",
            "summary": "Tests\u0020that\u0020process\u0020persists\u0020an\u0020entity\u0020for\u0020non\u002Ddelete\u0020operations.",
            "url": "classes/App-Tests-Infrastructure-StateProcessor-BaseStateProcessorTest.html#method_testProcessPersistsEntityForNonDeleteOperation"
        },                {
            "fqsen": "\\App\\Tests\\Infrastructure\\StateProcessor\\BaseStateProcessorTest\u003A\u003AtestProcessSoftDeletesEntityForDeleteOperation\u0028\u0029",
            "name": "testProcessSoftDeletesEntityForDeleteOperation",
            "summary": "Tests\u0020that\u0020process\u0020applies\u0020soft\u0020deletion\u0020for\u0020delete\u0020operations.",
            "url": "classes/App-Tests-Infrastructure-StateProcessor-BaseStateProcessorTest.html#method_testProcessSoftDeletesEntityForDeleteOperation"
        },                {
            "fqsen": "\\App\\Tests\\Infrastructure\\StateProcessor\\BaseStateProcessorTest\u003A\u003AtestProcessReturnsNullForInvalidData\u0028\u0029",
            "name": "testProcessReturnsNullForInvalidData",
            "summary": "Tests\u0020that\u0020process\u0020returns\u0020null\u0020when\u0020the\u0020data\u0020is\u0020not\u0020an\u0020EntityBase\u0020instance.",
            "url": "classes/App-Tests-Infrastructure-StateProcessor-BaseStateProcessorTest.html#method_testProcessReturnsNullForInvalidData"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\AuditableTraitTest",
            "name": "AuditableTraitTest",
            "summary": "Integration\u0020tests\u0020for\u0020the\u0020AuditableTrait.",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-AuditableTraitTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\AuditableTraitTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-AuditableTraitTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\AuditableTraitTest\u003A\u003AtestGetId\u0028\u0029",
            "name": "testGetId",
            "summary": "Tests\u0020the\u0020getId\u0020method\u0020of\u0020the\u0020AuditTrail\u0020entity.",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-AuditableTraitTest.html#method_testGetId"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\AuditableTraitTest\u003A\u003AtestAuditChanges\u0028\u0029",
            "name": "testAuditChanges",
            "summary": "Tests\u0020the\u0020auditChanges\u0020method\u0020in\u0020AuditableTrait.",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-AuditableTraitTest.html#method_testAuditChanges"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\AuditableTraitTest\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-AuditableTraitTest.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\Entity\\AuditTrailTest",
            "name": "AuditTrailTest",
            "summary": "Unit\u0020tests\u0020for\u0020the\u0020AuditTrail\u0020entity.",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-Entity-AuditTrailTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\Entity\\AuditTrailTest\u003A\u003AtestAuditTrailInitialization\u0028\u0029",
            "name": "testAuditTrailInitialization",
            "summary": "Tests\u0020the\u0020initialization\u0020of\u0020the\u0020AuditTrail\u0020entity\u0020and\u0020its\u0020getters.",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-Entity-AuditTrailTest.html#method_testAuditTrailInitialization"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\Entity\\AuditTrailTest\u003A\u003AtestAuditTrailSetters\u0028\u0029",
            "name": "testAuditTrailSetters",
            "summary": "Tests\u0020the\u0020setters\u0020for\u0020AuditTrail\u0020entity.",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-Entity-AuditTrailTest.html#method_testAuditTrailSetters"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\TestEntity",
            "name": "TestEntity",
            "summary": "Test\u0020entity\u0020that\u0020uses\u0020AuditableTrait\u0020for\u0020testing\u0020purposes.",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-TestEntity.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\TestEntity\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-TestEntity.html#method_setName"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\TestEntity\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-TestEntity.html#method_getName"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\TestEntity\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Audit-TestEntity.html#property_name"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Traits\\EventRaiserTraitTest",
            "name": "EventRaiserTraitTest",
            "summary": "Class\u0020EventRaiserTraitTest",
            "url": "classes/App-Tests-Unit-SharedKernel-Traits-EventRaiserTraitTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Traits\\EventRaiserTraitTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Traits-EventRaiserTraitTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Traits\\EventRaiserTraitTest\u003A\u003AtestRaiseEvent\u0028\u0029",
            "name": "testRaiseEvent",
            "summary": "Test\u0020that\u0020an\u0020event\u0020can\u0020be\u0020raised\u0020and\u0020retrieved.",
            "url": "classes/App-Tests-Unit-SharedKernel-Traits-EventRaiserTraitTest.html#method_testRaiseEvent"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Traits\\EventRaiserTraitTest\u003A\u003AtestRaiseMultipleEvents\u0028\u0029",
            "name": "testRaiseMultipleEvents",
            "summary": "Test\u0020that\u0020multiple\u0020events\u0020can\u0020be\u0020raised\u0020and\u0020retrieved.",
            "url": "classes/App-Tests-Unit-SharedKernel-Traits-EventRaiserTraitTest.html#method_testRaiseMultipleEvents"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Traits\\EventRaiserTraitTest\u003A\u003AtestClearEvents\u0028\u0029",
            "name": "testClearEvents",
            "summary": "Test\u0020that\u0020events\u0020can\u0020be\u0020cleared.",
            "url": "classes/App-Tests-Unit-SharedKernel-Traits-EventRaiserTraitTest.html#method_testClearEvents"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Traits\\EventRaiserTraitTest\u003A\u003A\u0024eventRaiser",
            "name": "eventRaiser",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Traits-EventRaiserTraitTest.html#property_eventRaiser"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\SoftDeleteTraitTest",
            "name": "SoftDeleteTraitTest",
            "summary": "Tests\u0020for\u0020the\u0020SoftDeleteTrait.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-SoftDeleteTraitTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\SoftDeleteTraitTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "Sets\u0020up\u0020the\u0020test\u0020environment\u0020with\u0020an\u0020anonymous\u0020class\u0020that\u0020uses\u0020SoftDeleteTrait.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-SoftDeleteTraitTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\SoftDeleteTraitTest\u003A\u003AtestSoftDelete\u0028\u0029",
            "name": "testSoftDelete",
            "summary": "Tests\u0020the\u0020delete\u0020and\u0020restore\u0020functionality\u0020of\u0020the\u0020SoftDeleteTrait.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-SoftDeleteTraitTest.html#method_testSoftDelete"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\SoftDeleteTraitTest\u003A\u003A\u0024softDeletable",
            "name": "softDeletable",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-SoftDeleteTraitTest.html#property_softDeletable"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\TimestampTraitTest",
            "name": "TimestampTraitTest",
            "summary": "Unit\u0020test\u0020for\u0020the\u0020TimestampTrait\u0020with\u0020validation\u0020checks.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-TimestampTraitTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\TimestampTraitTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-TimestampTraitTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\TimestampTraitTest\u003A\u003AtestCreatedAtFutureDateValidation\u0028\u0029",
            "name": "testCreatedAtFutureDateValidation",
            "summary": "Tests\u0020validation\u0020for\u0020a\u0020createdAt\u0020date\u0020in\u0020the\u0020future.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-TimestampTraitTest.html#method_testCreatedAtFutureDateValidation"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\TimestampTraitTest\u003A\u003AtestUpdatedAtFutureDateValidation\u0028\u0029",
            "name": "testUpdatedAtFutureDateValidation",
            "summary": "Tests\u0020validation\u0020for\u0020an\u0020updatedAt\u0020date\u0020in\u0020the\u0020future.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-TimestampTraitTest.html#method_testUpdatedAtFutureDateValidation"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\TimestampTraitTest\u003A\u003AtestSetCreatedAtValue\u0028\u0029",
            "name": "testSetCreatedAtValue",
            "summary": "Test\u0020that\u0020setCreatedAtValue\u0028\u0029\u0020sets\u0020the\u0020createdAt\u0020and\u0020updatedAt\u0020fields.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-TimestampTraitTest.html#method_testSetCreatedAtValue"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\TimestampTraitTest\u003A\u003AtestSetUpdatedAtValue\u0028\u0029",
            "name": "testSetUpdatedAtValue",
            "summary": "Test\u0020that\u0020setUpdatedAtValue\u0028\u0029\u0020sets\u0020the\u0020updatedAt\u0020field\u0020to\u0020the\u0020current\u0020DateTime.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-TimestampTraitTest.html#method_testSetUpdatedAtValue"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\TimestampTraitTest\u003A\u003A\u0024timestampable",
            "name": "timestampable",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-TimestampTraitTest.html#property_timestampable"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\TimestampTraitTest\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-TimestampTraitTest.html#property_validator"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\VersionableTraitTest",
            "name": "VersionableTraitTest",
            "summary": "Unit\u0020test\u0020for\u0020the\u0020VersionableTrait\u0020with\u0020validation\u0020checks.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-VersionableTraitTest.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\VersionableTraitTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-VersionableTraitTest.html#method_setUp"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\VersionableTraitTest\u003A\u003AtestDefaultVersion\u0028\u0029",
            "name": "testDefaultVersion",
            "summary": "Tests\u0020the\u0020default\u0020value\u0020of\u0020the\u0020version\u0020property.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-VersionableTraitTest.html#method_testDefaultVersion"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\VersionableTraitTest\u003A\u003AtestVersionPositiveConstraint\u0028\u0029",
            "name": "testVersionPositiveConstraint",
            "summary": "Tests\u0020that\u0020the\u0020version\u0020property\u0020fails\u0020validation\u0020when\u0020set\u0020to\u0020zero\u0020\u0028violating\u0020Positive\u0020constraint\u0029.",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-VersionableTraitTest.html#method_testVersionPositiveConstraint"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\VersionableTraitTest\u003A\u003A\u0024versionable",
            "name": "versionable",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-VersionableTraitTest.html#property_versionable"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait\\VersionableTraitTest\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/App-Tests-Unit-SharedKernel-Trait-VersionableTraitTest.html#property_validator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Tests\\Integration",
            "name": "Integration",
            "summary": "",
            "url": "namespaces/app-tests-integration.html"
        },                {
            "fqsen": "\\App\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/app-tests.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Domain\\Common\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-tests-unit-domain-common-entity.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Domain\\Common",
            "name": "Common",
            "summary": "",
            "url": "namespaces/app-tests-unit-domain-common.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Domain",
            "name": "Domain",
            "summary": "",
            "url": "namespaces/app-tests-unit-domain.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "namespaces/app-tests-unit.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\Common\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-tests-domain-common-entity.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\Common",
            "name": "Common",
            "summary": "",
            "url": "namespaces/app-tests-domain-common.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain",
            "name": "Domain",
            "summary": "",
            "url": "namespaces/app-tests-domain.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-tests-domain-usermanagement-entity.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement",
            "name": "UserManagement",
            "summary": "",
            "url": "namespaces/app-tests-domain-usermanagement.html"
        },                {
            "fqsen": "\\App\\Tests\\Domain\\UserManagement\\ValueObject",
            "name": "ValueObject",
            "summary": "",
            "url": "namespaces/app-tests-domain-usermanagement-valueobject.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure\\Persistence",
            "name": "Persistence",
            "summary": "",
            "url": "namespaces/app-tests-unit-infrastructure-persistence.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\Infrastructure",
            "name": "Infrastructure",
            "summary": "",
            "url": "namespaces/app-tests-unit-infrastructure.html"
        },                {
            "fqsen": "\\App\\Tests\\Infrastructure\\StateProcessor",
            "name": "StateProcessor",
            "summary": "",
            "url": "namespaces/app-tests-infrastructure-stateprocessor.html"
        },                {
            "fqsen": "\\App\\Tests\\Infrastructure",
            "name": "Infrastructure",
            "summary": "",
            "url": "namespaces/app-tests-infrastructure.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit",
            "name": "Audit",
            "summary": "",
            "url": "namespaces/app-tests-unit-sharedkernel-audit.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel",
            "name": "SharedKernel",
            "summary": "",
            "url": "namespaces/app-tests-unit-sharedkernel.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Audit\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-tests-unit-sharedkernel-audit-entity.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/app-tests-unit-sharedkernel-traits.html"
        },                {
            "fqsen": "\\App\\Tests\\Unit\\SharedKernel\\Trait",
            "name": "Trait",
            "summary": "",
            "url": "namespaces/app-tests-unit-sharedkernel-trait.html"
        }            ]
);
